import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/Sidebar/SideBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Learno+",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;

}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex flex-row">
                    <SideBar />
                    {children}
                </div>
            </body>
        </html>
    );
}
